### ISSUE TITLE
add version

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/scrnaseq_app#13]
Hi Marius,

I think it's time to create a version and changelog (version and major/minor changes. Maybe you can use the include.md file for this so it's available within the app. You guys were discussing all this recently.

cheers

**Comment by mariusrueve** [comment]
Added  [CHANGELOG.md](https://github.com/MHH-RCUG/scrnaseq_app/blob/master/CHANGELOG.md) to keep track of changes and Releases
