### ISSUE TITLE
Included images blurry 

### ISSUE THREAD

**Issue by ktrns** [MHH-RCUG/scrnaseq_app#18]
Hi there, 

You might want to include sharper images into the README.md, and also make sure the MHH logo is sharp. 

Best & thanks
Katrin

**Comment by mariusrueve** [comment]
@ktrns How can I make the images look sharper in the README.md? Because [this image](https://github.com/MHH-RCUG/scrnaseq_app/blob/master/www/Screenshot%202020-10-02%20220712.png) is sharp, but not when I include it.
