### ISSUE TITLE
Sizes of boxes in the app 

### ISSUE THREAD

**Issue by ktrns** [MHH-RCUG/scrnaseq_app#19]
Hi again, 

I am not an expert in Shiny, so I have no idea what is possible and what is not. 

I noticed that some text boxes look a bit odd dependent on the size of the window of the app. 

In the example, there is 
- zero space between the BROWSE box and the words on the right side
- DEFAULT SETTINGS FOR AXES reaches into the bright right side 

<img width="308" alt="Screenshot 2020-09-22 at 10 56 51" src="https://user-images.githubusercontent.com/9417927/93877005-0a0d4a00-fcd8-11ea-9aa8-6c9d0359ba9a.png">

Not the most important issue, but it might be nice to change this. 

Best and thanks
Katrin

**Comment by mariusrueve** [comment]
Fixed ✔️ https://github.com/MHH-RCUG/scrnaseq_app/commit/91f8481f981904b9ccc7a0538378dab2e90220cc
