### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by ktrns** [MHH-RCUG/scrnaseq_app#20]
Hi once more, 

This I consider the most important issue of my posted issues. 

I created a PR including adapted code for the plots. I noticed that you have three copies of the same code lines for plots, once for the images in the app, once for download of PNG, and once more for download of PDF. My advise is to create the ggplot objects once, render them for visualisation in the app, and print them into PNG and PDF. 

Best and thanks
Katrin

**Comment by mariusrueve** [comment]
Hello, I have fixed this Problem in https://github.com/MHH-RCUG/scrnaseq_app/commit/53bb3ebc7a27aa2edd8be2221fc73e59e4eb93e5 by creating global variables for the ggplot objects. Therefore there is only one chunk you have to look at if you want to change the plots.

Can I close this Issue or are there any further improvements to be made?

**Comment by ktrns** [comment]
Nice, thanks! You can close this issue. 

Best and thanks
Katrin
