### ISSUE TITLE
downloading fails without GUI error in singularity container

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/scrnaseq_app#23]
here the logs of multiple downloads failing:

[[1]]
Warning: Error in grid.newpage: could not open file 'FeaturePlot_FN1_ENSG00000115414.png'
  [No stack trace available]
[[1]]
Warning: Error in grid.newpage: could not open file 'FeaturePlot_FN1_ENSG00000115414.png'
  [No stack trace available]
[[1]]
Warning: Error in grid.newpage: could not open file 'FeaturePlot_FN1_ENSG00000115414.png'
  [No stack trace available]
Picking joint bandwidth of 3.44e-06
Picking joint bandwidth of 3.53e-06
Picking joint bandwidth of 0.104
[[1]]
Warning: Error in grid.newpage: could not open file 'FeaturePlot_FN1_ENSG00000115414.png'
  [No stack trace available]

**Comment by mariusrueve** [comment]
Is this error still present with the latest version of [dev](https://github.com/MHH-RCUG/scrnaseq_app/tree/dev)?

This error could already be fixed due to:
* changes to the creation and storage of plots
* the explicit use of the library zip and therefore masking zip from the utils package

**Comment by colindaven** [comment]
Hi @mariusrueve @tglomb 

I can't get downloads to work from the current (last night) singularity container (code from dev).

http://172.24.148.210:3838/

Please test in MHH network.  Using Windows server.

**Comment by Oliver-D-B** [comment]
I can confirm this as follows: I just tried the singularity at http://172.24.148.210:3838/ on my windows PC in Firefox. Overall app functionality was fine, but the download still didn't work instead was frozen with the 'Please wait...' message.
Working locally on our MHH internal (old) Windows server with the latest app worked fine, including the download.

**Comment by colindaven** [comment]
@mariusrueve It seems we might need a timeout (how long? 5 minutes ?) at least in this code section, whereafter an error should be reported:

https://github.com/MHH-RCUG/scrnaseq_app/blob/7cdc5a3b6669dbb56b1b6fdbb18bffa6ab817edc/scrnaseq_app.R#L458

Can you also report messages to the screen as part of shinyalert (at least for debugging) since it's difficult or impossible to see where it is freezing. It might be nice to at least report it to the server logs (stacktrace), but optionally to the screen would also be good. What do you think ?
