### ISSUE TITLE
added singularity recipes

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/scrnaseq_app#25]
HI @mariusrueve 

I added the singularity recipes as a subfolder to dev. Please check this had no unintended impacts ?

Are you happy with this change ?

https://github.com/MHH-RCUG/scrnaseq_app/tree/dev/singularity

cheers

**Comment by mariusrueve** [comment]
Sorry for the late answer. Yes I think it's a great improvement to have everything in one place. Once everything is pulled into master I will create a new and first official release.
