### ISSUE TITLE
Improve user experience

### ISSUE THREAD

**Issue by tglomb** [MHH-RCUG/scrnaseq_app#26]
It would be nice if the user gets a message/feedback after the file import and during the download process that there is still an ungoing process. Thus the user knows that the app is currently not available or is still working.

**Comment by ktrns** [comment]
I agree on this one. It would be nice to get a status message to say, for example, that the upload of the RDS file is finished.

**Comment by mariusrueve** [comment]
Fixed ✔️ https://github.com/MHH-RCUG/scrnaseq_app/commit/ab4e11e4c1543650393ae550b7a23adce403f46d

The notification looks like this
![Screenshot 2020-10-02 162822](https://user-images.githubusercontent.com/44000950/94934677-59b7f680-04cc-11eb-9e54-275a7793c233.png)

**Comment by mariusrueve** [comment]
Is this kind of notification fine?

**Comment by Oliver-D-B** [comment]
Dear @mariusrueve,
probably @tglomb refered to the obviously large gap starting when the blue bar is already completely filled until the upload is actually done and genes are selectable (still 15 seconds!). Could we integrate a message like 'please wait, .rps file is still uploading' that simply disappears when upload is complete (thus the other way round as currently implemented)?

**Comment by mariusrueve** [comment]
If I use the default theme the upload progress is displayed like this:
![Screenshot 2020-10-04 201110](https://user-images.githubusercontent.com/44000950/95023535-e81faa00-067d-11eb-85e7-ca534041d23a.png)

If a simple progress bar + "upload completed" is enough, we can stick to the default theme.

**Comment by ktrns** [comment]
"Upload completed" looks great to me!

**Comment by Oliver-D-B** [comment]
yes, if this new bar is more synchronized with actual progress (e.g. once the bar is completely filled, data is accessible), than its fine

**Comment by tglomb** [comment]
Hi all, I think I have to clarify my issue more precisely.  

We have three processes that need some time where the user should get to know that the app is unavailable.  

1. Upload process of rds file
   1. Upload of rds file
   1. Extracting gene names from Seurat object and fill "Genes" list

1. Upload process of Excel file
   1. Upload of Excel file
   1. Extracting gene names from Excel file and set seelction in "Genes" list

1. Download selection of plots
   1. Generation of zip archive

The steps 1i) and 2i) were already solved and fine so far with the progressbars.
Steps 1ii), 2ii) and 3i) are time consuming (some seconds) were the app seems to be available for the user but it's not. **And these are the steps where I thought an improvement of the user experience would be fine.**

My suggestions would be either
- disable the user to perform an action (grey out the user interface of the app) **and/or**
- show some kind of popup/message box in the middle of the app saying something like "Upload in progress", "Download in progress". This popup/message box disapears when the processes are finished  
  - some ideas where to start to search for a solution  
https://shiny.rstudio.com/reference/shiny/0.14/showNotification.html  
https://stackoverflow.com/questions/44112000/move-r-shiny-shownotification-to-center-of-screen  
https://deanattali.com/blog/shinyalert-package/

Don't hesitate to contact me if you have further questions.

**Comment by mariusrueve** [comment]
Added a pop-up for the upload of .rds file and the creation of files + download in https://github.com/MHH-RCUG/scrnaseq_app/commit/86d522e8b873b8024e572238ec4bafe25a90d03b with `shinyalert`. If these notifications are fine I can add one for the upload of the excel file.

I made the sidebarPanel dynamic. Therefor only the option for uploading .rds is shown when starting the app.
When the file have been uploaded succesfully the rest of the UI gets rendered.

The download now shows an error message if there are no genes selected and asks the user to select some before downloading.

**Comment by tglomb** [comment]
Looks nice now and the user gets a proper info about waiting times.  
You could implement this for the Excel file upload as well as you suggested.

Good, that you catched the "empty" download already. :+1:

**Comment by mariusrueve** [comment]
Already implemented the alert for the excel upload in the latest commit.

________________________________
Von: tglomb <notifications@github.com>
Gesendet: Thursday, October 8, 2020 4:58:02 PM
An: MHH-RCUG/scrnaseq_app <scrnaseq_app@noreply.github.com>
Cc: Marius R <marius.rueve@live.de>; Mention <mention@noreply.github.com>
Betreff: Re: [MHH-RCUG/scrnaseq_app] Improve user experience (#26)


Looks nice now and the user gets a proper info about waiting times.
You could implement this for the Excel file upload as well as you suggested.

Good, that you catched the "empty" download already. 👍

**Comment by tglomb** [comment]
Okay, that's great. Thank you.
