### ISSUE TITLE
No sign .rds file has been uploaded and processed

### ISSUE THREAD

**Issue by dimialex** [MHH-RCUG/scrnaseq_app#27]
At the beginning, once having selected a Seurat file to upload, there is no sign that the .rds file has been indeed uploaded and processed. It is, therefore, not clear the user can move to the next step and select the genes of interest to be plotted

**Comment by mariusrueve** [comment]
Please look at #26. Do you think this kind of notification is good enough?

**Comment by dimialex** [comment]
yes, that's fine
