### ISSUE TITLE
Broken screenshot before the "Built With" header in the Help tab within the App

### ISSUE THREAD

**Issue by dimialex** [MHH-RCUG/scrnaseq_app#29]
Hi again,
within the app, in the Help tab, Section "About The Project", there is a broken screenshot before the "Built With" header
Best,
Dimitra

**Comment by mariusrueve** [comment]
Fixed ✔️ https://github.com/MHH-RCUG/scrnaseq_app/commit/9520c7b75f4dbc9453573d8dfe6421fe95ddc2e9
