### ISSUE TITLE
XY axes typo and settings

### ISSUE THREAD

**Issue by dimialex** [MHH-RCUG/scrnaseq_app#30]
Dear all,
when selecting the xy axes settings, there is a typo and both axes are labelled as "X-Axis (px):"
[Edit] I see this is already a [closed issue](https://github.com/MHH-RCUG/scrnaseq_app/issues/15) and should therefore be solved in the next release.
Additionally, would it be possible to have a button for keeping/or not the ratio between the two axes fixed when editing one of the two?
Best,
Dimitra

**Comment by colindaven** [comment]
I think this was solved already in master in the recent container I was looking at. Ping @mariusrueve 
Thanks

**Comment by mariusrueve** [comment]
Fixed ✔️
