### ISSUE TITLE
Example Excel file upload does not work

### ISSUE THREAD

**Issue by dimialex** [MHH-RCUG/scrnaseq_app#31]
Dear all,
I just tried to upload the [example Excel file](https://owncloud.gwdg.de/index.php/s/ZwY0iVPji6uBVKO) provided by you and it seems that the upload did not work. I cannot select any genes and no plots are being created, throwing such warnings
<pre>
Warning: Error in UseMethod: no applicable method for 'DefaultAssay' applied to an object of class "NULL"
  [No stack trace available]
</pre>
I have cleaned up workspace, restarted R, tried the app also in the browser and the result is the same, no genes uploaded.
Best,
Dimitra

**Comment by mariusrueve** [comment]
I tried to recreate this problem, but the excel files works for me.
I'll try to figure out the cause of this error and fix it.

**Comment by colindaven** [comment]
- [ ] Colin - check upload works from most recent singularity code and container

**Comment by dimialex** [comment]
Tried it again and it works, I'm closing this, thanks
