### ISSUE TITLE
Documentation: broken links

### ISSUE THREAD

**Issue by dimialex** [MHH-RCUG/scrnaseq_app#32]
Dear all,
on the [main page](https://github.com/MHH-RCUG/scrnaseq_app), the following links are broken/leading to nowhere:
https://github.com/MHH-RCUG/scrnaseq_app/blob/master/select-genes-through-ui
https://github.com/MHH-RCUG/scrnaseq_app/blob/master/select-genes-through-an-Excel-file-with-header
https://github.com/MHH-RCUG/scrnaseq_app/blob/master/select-genes-through-an-Excel-file-without-header
Best,
Dimitra

**Comment by colindaven** [comment]
Thanks, fixed in
https://github.com/MHH-RCUG/scrnaseq_app/pull/24
