### ISSUE TITLE
Splitting app.R into UI.R + server.R

### ISSUE THREAD

**Issue by mariusrueve** [MHH-RCUG/scrnaseq_app#37]
I think the app has too much code for app.R.
Splitting the file into UI.R and server.R will result in an easier navigation.

**Comment by colindaven** [comment]
I would suggest updating master first. The singularity code will have to change, I'm sure you can do this (very easy) and I can test it.

I added the shinyalert package to the singularity container in my test repo and will PR to this repo soon.

Are there any other new packages (is zip specifically needed ?), will test soon.

**Comment by mariusrueve** [comment]
I will make some minor changes and update master. 

I think zip is not needed for singularity only if the app is run on windows. But it would be great if we can test this, to be sure.
