### ISSUE TITLE
max upload size

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/scrnaseq_app#4]
Hi @tglomb 

how big are the max upload files (RDS) you produce from Seurat ?

At the moment the max size is 300mb, but it should be bigger I guess ? This is ok for the test data.

`options(shiny.maxRequestSize=300*1024^2)`

cheers

**Comment by mariusrueve** [comment]
Can be adjusted easily. I just need a rough number, because I don't know how big the files can get either.

@ktrns Do you know if 300 MB is big enough?

**Comment by colindaven** [comment]
ping @tglomb Can you give us an answer please ? Thanks

**Comment by ktrns** [comment]
Hi all, 
I double checked the size of my scrnaseq.rds file of a recent 10X project with ~10k cells, and it is about 3GB. I guess we can look into reducing this, but it is what it is for now. 
Best
Katrin

**Comment by tglomb** [comment]
Hi,  
I checked a current project. If I process the samples separately the size of the rds files are about 500GB but an analysis of 8 samples together gets up to 4.3GB.  
Do you think a limit of 5GB would be to much?

**Comment by colindaven** [comment]
5GB sounds alright. We might get problems trying to load a file >4GB, it's not so easy with many web technologies (eg apache). I'm not sure if shiny can handle that, so we need to test this.
