### ISSUE TITLE
singularity container: shinyjs .. new ?

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/scrnaseq_app#42]
Hi @mariusrueve 

what's with shinyjs ? Does shinyalert (new) rely on this ?
Do we need this to be specifically added in the recipe ?

Please provide a comprehensive list of R packages you need when you change something, or even better, just directly edit the singularity recipes.

cheers

```

singularity exec ../../scrnaseq_app.simg     R -e "options('shiny.port'=3838,shiny.host='0.0.0.0'); shiny::runApp('/data/scrnaseq_app/scrnaseq_app.R')"

R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> options('shiny.port'=3838,shiny.host='0.0.0.0'); shiny::runApp('/data/scrnaseq_app/scrnaseq_app.R')
Loading required package: shiny

Attaching package: ‘shinyalert’

The following object is masked from ‘package:shiny’:

    runExample

Error in library(shinyjs) : there is no package called ‘shinyjs’
Calls: <Anonymous> ... sourceUTF8 -> eval -> eval -> ..stacktraceon.. -> library
Execution halted

```

**Comment by colindaven** [comment]
So I added shinyjs - correctly, now I need zip. Any more ??
```

Attaching package: ‘shinyjs’

The following object is masked from ‘package:shinyalert’:

    runExample

The following object is masked from ‘package:shiny’:

    runExample

The following objects are masked from ‘package:methods’:

    removeClass, show

Error in library(zip) : there is no package called ‘zip’

```

**Comment by mariusrueve** [comment]
Yes shinyjs is new, I use this to close shinyalerts on certain events.
Currently these are in the code:

```
library(shiny)
library(Seurat)
library(ggplot2)
library(shinythemes)
library(markdown)
library(readxl)
library(shinyalert)
library(shinyjs)
library(zip)
```

I need to reconsider some packages and if they are really needed.

**Comment by colindaven** [comment]
Thanks Marius,

the container is running again after adding those new libs. 

cheers,
Colin


> options('shiny.port'=3838,shiny.host='0.0.0.0'); shiny::runApp('/data/scrnaseq_app/scrnaseq_app.R')
Loading required package: shiny

Attaching package: ‘shinyalert’

The following object is masked from ‘package:shiny’:

    runExample


Attaching package: ‘shinyjs’

The following object is masked from ‘package:shinyalert’:

    runExample

The following object is masked from ‘package:shiny’:

    runExample

The following objects are masked from ‘package:methods’:

    removeClass, show


Attaching package: ‘zip’

The following objects are masked from ‘package:utils’:

    unzip, zip

**Comment by Oliver-D-B** [comment]
great, many thanks to both of you @colindaven @mariusrueve !!!
