### ISSUE TITLE
No actual change in resolution for downloaded pdf files

### ISSUE THREAD

**Issue by Oliver-D-B** [MHH-RCUG/scrnaseq_app#43]
At present, any change in resolution settings (deviation from default) applies only to the png outputs not to the pdfs

**Comment by Oliver-D-B** [comment]
The problem here is that the relative size proportion of pure image elements versus axis text labels can't be directly adressed/changed in the app (with regard to the **pdf** outcome). The current functionality doesn't allow for an optimized visual display/adjustment of the **entire** panel (**graphics and text**) as pdf. 
In other words, presently, the pdf always just **represents** the 1280x720 resolution, which doesn't always provide a good relation of graphics elements versus axis text labels (documented in the following example with obviously too small axis text labels). 

[violin raw FTH1 different resolution examples.pptx](https://github.com/MHH-RCUG/scrnaseq_app/files/5418394/violin.raw.FTH1.different.resolution.examples.pptx)

We need to discuss possibilities of respective adjustment options for the user (image elements versus axis texts).

**Comment by mariusrueve** [comment]
Note: use axes with ratio for pdf

**Comment by mariusrueve** [comment]
Fixed ✔️ 285170c5038b003e8c06a1bef5fa02c125d5503e

I used a ratio of 1 in = 96 pixel.

With very low numbers (pixel) the pdf file seems a bit off compared to the png. But I guess if you want a low resolution a png file should be fine aswell.
