### ISSUE TITLE
No visible change in resolution specific to Dot plot

### ISSUE THREAD

**Issue by Oliver-D-B** [MHH-RCUG/scrnaseq_app#44]
Specific to the dot plot panel, an executed change in the resolution settings (deviations from default) is not directly visible in the app, even though it is anyhow considered in downloaded png files.

**Comment by mariusrueve** [comment]
I think this is cause by the fact that a pdf file is vector based. Therefore it doesn't use pixel and has always the best possible resolution.

**Comment by Oliver-D-B** [comment]
What I meant here was that for all other plots, applied resolution changes are visible in the app's window (in real time so to say) but only for the dot plot, no changes at all occur in this window

**Comment by colindaven** [comment]
I can confirm what Oliver is saying, testing in the new Singularity container from last night.

**Comment by mariusrueve** [comment]
Fixed ✔️ https://github.com/MHH-RCUG/scrnaseq_app/commit/14ec1e7d197688f2a7ede33fc49c0a69e7c96deb
