### ISSUE TITLE
Synchronization of color assignments between scrnaseq-analysis report and app

### ISSUE THREAD

**Issue by Oliver-D-B** [MHH-RCUG/scrnaseq_app#45]
There is no direct synchronization of color assignments between what is used in the scrnaseq-analysis report and what is shown in this app (e.g. colors specifically assigned to individual clusters for a given project). Actually, color assignments differ between report and app and this is confusing for users. Is there any way to transmit all relevant coloring information from a given report (or better from the report’s output folder) to be available for upload into the app (e.g. along with the .rds file)? Maybe @ktrns can help to provide an additional output from the main scrnaseq-analysis script (as input for the app)?

**Comment by ktrns** [comment]
Hi there, 

That is totally possible and a good idea. We should add colour assignments to the meta data. I will talk to @andpet0101 about it, he handled the meta data so far. I would think that we just add another two columns for `colour_sample` and `colour_cluster`. 

Our plan is to soon-ish change a few more things on the main script, so I can directly incorporate this change. 

Best
Katrin

**Comment by andpet0101** [comment]
Hi,

I think we can included named colour lists for sample and cluster in the misc slot of the Seurat object. One can even think about a named list for colours where the names correspond to metadata column names (`seurat_cluster` for cluster, `orig.ident` for sample) and the values are colour lists specifing the colour for each unique value of that column.

Best,

Andreas
