### ISSUE TITLE
‘Check for Headers’ element is dispensable

### ISSUE THREAD

**Issue by Oliver-D-B** [MHH-RCUG/scrnaseq_app#46]
In order to simplify the workflow for end-users: Why not completely removing the element ‘Check if Excel file contains Headers’ and always considering the upmost entry in Excel already as potential ID or Gene. If this entry is indeed a header, no problem at all, the subsequent algorithm will simply not find any corresponding feature in the scanned ID matrix (as for wrong entries or any IDs not contained in the scanned matrix).

**Comment by mariusrueve** [comment]
Fixed ✅  https://github.com/MHH-RCUG/scrnaseq_app/commit/77a6d98c37b6c80c2f4f40db8bb2093f3bfa4f89
