### ISSUE TITLE
Integration of the RCUG LOGO

### ISSUE THREAD

**Issue by Oliver-D-B** [MHH-RCUG/scrnaseq_app#49]
The RCUG LOGO should be integrated in addition to the MHH LOGO.

**Comment by mariusrueve** [comment]
Maybe you can give me the MHH and RCUG logo with good quality. I just took the MHH logo from the webpage and therefore has not he best quality ([MHH Logo I used](https://raw.githubusercontent.com/MHH-RCUG/scrnaseq_app/master/www/MHH.png)).

**Comment by mariusrueve** [comment]
Added the MHH logo with higher resolution 541a03fc8b1cc3d060628cb624005963da518c5e.

I only need the RCUG logo now.

**Comment by Oliver-D-B** [comment]
here are just two versions, please try if the resolution and file formats are acceptable, if not we may provide a different file

[RCU_Genomics_Logo_final_isoliert.pdf](https://github.com/MHH-RCUG/scrnaseq_app/files/5460543/RCU_Genomics_Logo_final_isoliert.pdf)


![RCU Genomics LOGO als Png](https://user-images.githubusercontent.com/64102622/97617501-23fc2400-1a1e-11eb-8df7-386e2a4fb27d.png)

**Comment by Oliver-D-B** [comment]
the original comes from powerpoint

[RCU_Genomics_Logo_final_isoliert.pptx](https://github.com/MHH-RCUG/scrnaseq_app/files/5460554/RCU_Genomics_Logo_final_isoliert.pptx)

**Comment by Oliver-D-B** [comment]
one more pdf

[RCUG Logo.pdf](https://github.com/MHH-RCUG/scrnaseq_app/files/5460765/RCUG.Logo.pdf)

**Comment by mariusrueve** [comment]
Fixed ✔️ 42ae467532fc9bf6521800c8260008d69e558e30
![Screenshot 2020-11-01 185424](https://user-images.githubusercontent.com/44000950/97810383-b21d1800-1c73-11eb-961e-f2cf13410e57.png)

Issue can be closed if okay!
