### ISSUE TITLE
Limiting search functionality in Excel to columns 1 and 2

### ISSUE THREAD

**Issue by Oliver-D-B** [MHH-RCUG/scrnaseq_app#51]
The search for IDs and Gene names in the Excel file is obviously not strictly limited to columns 1 and 2 as stated in the help section. Even GeneID and Gene name entries at the lower right corner of the Excel matrix (e.g. column 16384, row 1048576) are still considered accordingly. Even though this is not a severe problem per se, we might anyhow consider to limit search functionality to columns 1 and 2 as stated to avoid potential conflicts in future.

**Comment by mariusrueve** [comment]
Fixed ✅ https://github.com/MHH-RCUG/scrnaseq_app/commit/77a6d98c37b6c80c2f4f40db8bb2093f3bfa4f89
