### ISSUE TITLE
Legend text in ‘Help’ section needs minor adjustment

### ISSUE THREAD

**Issue by Oliver-D-B** [MHH-RCUG/scrnaseq_app#52]
The following text in the ‘Help’ section needs to be adapted, from: 

“This app is dependent on data generated by Seurat, which must be run first. The app reads an .rds file which contains the Seurat object and all associated data. The user can then select genes through a list or an Excel file (.xlsx). The expression of these genes is then displayed in a) t-SNE plots b) Ridge plots c) violin plots or d) dot plots. The generated plots can then be downloaded in .pdf and .png format.” 

to 

“This app is dependent on data generated by Seurat, which must be run first. The app reads an .rds file which contains the Seurat object and all associated data. The user can then select genes through a list or an Excel file (.xlsx). The expression of these genes is then displayed in a) **UMAP** plots b) Ridge plots c) **V**iolin plots **d) Dot plots or e) a global Heatmap.** The generated plots can then be downloaded in .pdf and .png format.”

**Comment by mariusrueve** [comment]
Fixed ✔️ 460259ba2f77f7e004e6062827b23f20452728b0
