### ISSUE TITLE
Security options - all greyed out

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/scrnaseq_app#54]
Hi,

this is likely due to the poor state of support for certificates and HTTPS on our campus, but to report anyway.

In windows I can run the Shiny page normally (in a singularity container) and access it without security problems.

In Linux everything is greyed out in both Firefox and Linux.

@mariusrueve I think we can just leave this issue here as a note, it's likely not critical.

cheers
Colin

**Comment by Oliver-D-B** [comment]
I just tried the singularity at http://172.24.148.210:3838/ on my windows PC in Firefox. Overall app functionality was fine, but the download still didn't work instead was frozen with the 'Please wait...' message
