### ISSUE TITLE
Help section

### ISSUE THREAD

**Issue by kosankem** [MHH-RCUG/scrnaseq_app#66]
- [x] The names/subtitles of "select genes" categories are different in the import data section and the help section
- [x] "select genes" category "select through genen list" is missing in the help section

- [x] The distance between the columns in the table template should be lager to suport reading of the column headings
- [x] An indication whether the column headings have to be included in the uploaded table or not, is missing

Here some correction to comma placement (as far as I know) and phrasing
- [x] First of all (Comma) .... and then in the same line no comma in front of "which"
- [x] In order to find certain genes (Comma) ....
- [x] Once precessed (Comma) ...
- [x] If you only would like to export certain plots, .... uncheck the unrequested ones.
- [x] Personally, I prefer to use "data" with the plural form like "data have been processed", but the singular form that you used is also possible in this context, I think

**Comment by mariusrueve** [comment]
Fixed https://github.com/MHH-RCUG/scrnaseq_app/commit/a0e4ee53288c648dda3f8db36aa326832a0f8122 ✔
