### ISSUE TITLE
shinythemes problem

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/scrnaseq_app#7]
Error now when starting exec on the container, build was fine.

R3.6.3 (is this expected or are you on R4.0 Marius ? )

```
options('shiny.port'=3838,shiny.host='0.0.0.0'); shiny::runApp('/data/scrnaseq_app/scrnaseq_app.R')
Loading required package: shiny
Error in library(shinythemes) : there is no package called ‘shinythemes’
```

Workaround mentioned in this thread

https://community.rstudio.com/t/error-when-publishing-shiny-app-to-shinyapps-io-error-error-in-value-3l-cond-there-is-no-package-called-shinythemes/23178

You can copy or run the container, locations of the code and app are:

```

/ngsssd1/rcug/singularity/sameith_app/singularity_scrna_app
/ngsssd1/rcug/singularity/sameith_app/
```

Do you want to implement the workaround (changing file names?) or shall I try something else ?

**Comment by mariusrueve** [comment]
Because I use hpc06 I use R4.0, RStdio asked me to update everthing.

Also I'm using these libraries:
```
library(shiny)
library(Seurat)
library(ggplot2)
library(shinythemes)
library(markdown)
```
```
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base    

other attached packages:
[1] markdown_1.1      shinythemes_1.1.2 ggplot2_3.3.2     Seurat_3.1.5      shiny_1.5.0 
```

I use shinythemes, because it looks way better than the default UI of shiny. 
If you need to, you can comment line 28 `  theme = shinytheme("paper"),`.

**Comment by colindaven** [comment]
Ok, I didn't have shinythemes on the R package list. I'll try to get it to pull R4.0 as well, makes sense

**Comment by colindaven** [comment]
REsolved, works
